---
abstract: 'A Password safe'
author:
  - 'Copyright (C) 2011 by Daniel Friesel E<lt>derf@finalrewind.orgE<gt>'
build_requires:
  Test::Command: 0
  Test::Compile: 0
  Test::Fatal: 0
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Raps2
provides:
  App::Raps2:
    file: lib/App/Raps2.pm
    version: 0.3
  App::Raps2::Password:
    file: lib/App/Raps2/Password.pm
    version: 0.3
  App::Raps2::UI:
    file: lib/App/Raps2/UI.pm
    version: 0.3
requires:
  Crypt::CBC: 0
  Crypt::Eksblowfish: 0
  Crypt::Eksblowfish::Bcrypt: 0
  File::BaseDir: 0
  File::Path: 2.0605
  File::Slurp: 0
  POSIX: 0
  Term::ReadLine: 0
  perl: v5.10.0
version: 0.3
